services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    restart: unless-stopped
    volumes:
      - pg_data:/var/

  web:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  pg_data: